project:
  type: website
  output-dir: docs

website:
  title: "PLMAND002"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - report.qmd
      - Appendix.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
