project:
  type: website
  output-dir: docs

website:
  title: "A Quarto Website, PLMAND002"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - addition.qmd
      - Appendix.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
