---
title: "Welcome!"
---

Name: Andrea Plumbley
Student Number: PLMAND002
Course Code: STA5073Z

This is a website for the submission of Assignment 1. The report for submission can be found on the Asignment 1: Report tab. 


## Plagiarism Declaration

1. I know that plagiarism is wrong. Plagiarism is to use another’s work and pretend that it is
one’s own.

2. I have used a generally accepted citation and referencing style. Each contribution to, and
quotation in, this tutorial/report/project from the work(s) of other people has been
attributed, and has been cited and referenced.

3. This tutorial/report/project is my own work.

4. I have not allowed, and will not allow, anyone to copy my work with the intention of
passing it off as his or her own work.

5. I acknowledge that copying someone else’s assignment or essay, or part of it, is wrong,
and declare that this is my own work.

Note that agreement to this statement does not exonerate you from the University’s plagiarism rules
(http://www.uct.ac.za/uct/policies/plagiarism_students.pdf).

Signature: A Plumbley
Date: 16/10/2023